import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Pencil, Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/AppButton";
import { TextInput } from "@/components/ui/Field";
import { Modal } from "@/components/Modal/Modal";
import { ConfirmModal } from "@/components/admin/ConfirmModal";
import { EmptyState, ErrorState, TableSkeleton } from "@/components/Loading/Loading";
import { useToast } from "@/context/ToastContext";
import { couponService, type Coupon } from "@/services/couponService";
import { formatCurrency } from "@/utils/format";

export const Route = createFileRoute("/admin/coupons")({ head: () => ({ meta: [{ title: "Coupons — Ilarooh Admin" }] }), component: AdminCoupons });

type Form = { code: string; type: "percentage" | "fixed"; value: string; minOrderAmount: string; maxDiscount: string; startsAt: string; expiresAt: string; usageLimit: string; active: boolean };
const blank: Form = { code: "", type: "percentage", value: "10", minOrderAmount: "0", maxDiscount: "", startsAt: "", expiresAt: "", usageLimit: "", active: true };
const dateInput = (value: string | null) => value ? new Date(value).toISOString().slice(0, 16) : "";

function AdminCoupons() {
  const qc = useQueryClient(); const { notify } = useToast(); const [editing, setEditing] = useState<Coupon | null>(null); const [creating, setCreating] = useState(false); const [form, setForm] = useState<Form>(blank); const [pendingDelete, setPendingDelete] = useState<Coupon | null>(null);
  const query = useQuery({ queryKey: ["admin-coupons"], queryFn: couponService.list });
  const save = useMutation({ mutationFn: async () => { const payload = { code: form.code, type: form.type, value: Number(form.value), minOrderAmount: Number(form.minOrderAmount || 0), maxDiscount: form.maxDiscount ? Number(form.maxDiscount) : null, startsAt: form.startsAt ? new Date(form.startsAt).toISOString() : new Date().toISOString(), expiresAt: form.expiresAt ? new Date(form.expiresAt).toISOString() : null, usageLimit: form.usageLimit ? Number(form.usageLimit) : null, active: form.active }; return editing ? couponService.update(editing._id, payload) : couponService.create(payload); }, onSuccess: () => { void qc.invalidateQueries({ queryKey: ["admin-coupons"] }); notify(editing ? "Coupon updated" : "Coupon created", { variant: "success" }); setEditing(null); setCreating(false); }, onError: (e) => notify(e instanceof Error ? e.message : "Couldn't save coupon", { variant: "error" }) });
  const remove = useMutation({ mutationFn: (id: string) => couponService.remove(id), onSuccess: () => { void qc.invalidateQueries({ queryKey: ["admin-coupons"] }); setPendingDelete(null); notify("Coupon deleted", { variant: "success" }); }, onError: () => notify("Couldn't delete coupon", { variant: "error" }) });
  const openEdit = (c: Coupon) => { setEditing(c); setForm({ code: c.code, type: c.type, value: String(c.value), minOrderAmount: String(c.minOrderAmount), maxDiscount: c.maxDiscount == null ? "" : String(c.maxDiscount), startsAt: dateInput(c.startsAt), expiresAt: dateInput(c.expiresAt), usageLimit: c.usageLimit == null ? "" : String(c.usageLimit), active: c.active }); };
  const openCreate = () => { setEditing(null); setForm(blank); setCreating(true); };
  const modalOpen = creating || !!editing;
  return <div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="eyebrow text-accent">Marketing</p><h1 className="mt-1 text-3xl font-semibold">Coupons</h1></div><Button variant="accent" onClick={openCreate}><Plus className="size-4" /> New coupon</Button></div>
    {query.isLoading ? <TableSkeleton /> : query.isError ? <ErrorState onRetry={() => void query.refetch()} /> : (query.data ?? []).length === 0 ? <EmptyState title="No coupons yet" description="Create a discount code customers can use at checkout." /> : <div className="overflow-hidden rounded-3xl border border-border bg-card shadow-soft"><table className="w-full text-left text-sm"><thead><tr className="border-b border-border text-xs uppercase tracking-wider text-muted-foreground"><th className="px-5 py-3">Code</th><th className="px-5 py-3">Discount</th><th className="hidden px-5 py-3 sm:table-cell">Minimum</th><th className="hidden px-5 py-3 md:table-cell">Usage</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody>{(query.data ?? []).map((c) => <tr key={c._id} className="border-b border-border last:border-0"><td className="px-5 py-3 font-semibold">{c.code}</td><td className="px-5 py-3">{c.type === "percentage" ? `${c.value}%` : formatCurrency(c.value)}</td><td className="hidden px-5 py-3 sm:table-cell">{formatCurrency(c.minOrderAmount)}</td><td className="hidden px-5 py-3 md:table-cell">{c.usageCount}{c.usageLimit == null ? "" : ` / ${c.usageLimit}`}</td><td className="px-5 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${c.active ? "bg-success/10 text-success" : "bg-secondary text-muted-foreground"}`}>{c.active ? "Active" : "Off"}</span></td><td className="px-5 py-3"><div className="flex justify-end gap-2"><Button variant="outline" size="icon" onClick={() => openEdit(c)}><Pencil className="size-4" /></Button><Button variant="destructive" size="icon" onClick={() => setPendingDelete(c)}><Trash2 className="size-4" /></Button></div></td></tr>)}</tbody></table></div>}
    <Modal open={modalOpen} onClose={() => { setCreating(false); setEditing(null); }} title={editing ? "Edit coupon" : "New coupon"} footer={<><Button variant="outline" onClick={() => { setCreating(false); setEditing(null); }}>Cancel</Button><Button variant="accent" loading={save.isPending} onClick={() => void save.mutate()}>Save coupon</Button></>}>
      <div className="space-y-4"><TextInput value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value.toUpperCase() })} placeholder="WELCOME10" /><div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">Type<select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value as Form["type"] })} className="mt-1 h-10 w-full rounded-xl border border-border bg-background px-3"><option value="percentage">Percentage</option><option value="fixed">Fixed ₹</option></select></label><label className="text-sm font-medium">Value<TextInput value={form.value} onChange={(e) => setForm({ ...form, value: e.target.value })} type="number" /></label></div><div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">Min order<TextInput value={form.minOrderAmount} onChange={(e) => setForm({ ...form, minOrderAmount: e.target.value })} type="number" /></label><label className="text-sm font-medium">Max discount<TextInput value={form.maxDiscount} onChange={(e) => setForm({ ...form, maxDiscount: e.target.value })} type="number" placeholder="Optional" /></label></div><div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">Starts<TextInput value={form.startsAt} onChange={(e) => setForm({ ...form, startsAt: e.target.value })} type="datetime-local" /></label><label className="text-sm font-medium">Expires<TextInput value={form.expiresAt} onChange={(e) => setForm({ ...form, expiresAt: e.target.value })} type="datetime-local" /></label></div><label className="text-sm font-medium">Usage limit<TextInput value={form.usageLimit} onChange={(e) => setForm({ ...form, usageLimit: e.target.value })} type="number" placeholder="Unlimited" /></label><label className="flex items-center gap-3 text-sm font-medium"><input type="checkbox" checked={form.active} onChange={(e) => setForm({ ...form, active: e.target.checked })} /> Active</label></div>
    </Modal>
    <ConfirmModal open={!!pendingDelete} onClose={() => setPendingDelete(null)} onConfirm={() => pendingDelete && remove.mutate(pendingDelete._id)} title="Delete coupon" description={pendingDelete ? `Remove ${pendingDelete.code} permanently?` : ""} loading={remove.isPending} />
  </div>;
}
